### ISSUE TITLE
-XX:-OmitStackTraceInFastThrow Is Backwards

### ISSUE THREAD

**Issue by rdifalco** [FoxxMD/intellij-jvm-options-explained#1]
This actually prevents preallocated exceptions because of the '-'. I think based on your advice that you want this to be a '+'.

**Comment by FoxxMD** [comment]
I'm not sure I understand what the difference is. I have written

>  Using this option prevents stack traces from being generated for these exceptions 

Is that not what you are saying? The '-' variant is what [jetbrains](https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties) has listed in their default jvm options.

**Comment by rdifalco** [comment]
I may have misread, I thought you were recommending TO omit the stack trace unless debugging. But your tl;dr version at the top has a '-' instead of a '+'. You need to specify with a '+' to omit the stack traces associated with cached exceptions.

**Comment by FoxxMD** [comment]
I *am* trying to omit stack traces unless debugging 😂 

Ok, so let me make sure I have this figured out. 

From the release notes where I found this option:

> The compiler in the server VM now provides correct stack backtraces for all "cold" built-in exceptions. For performance purposes, when such an exception is thrown a few times, the method may be recompiled. After recompilation, the compiler may choose a faster tactic using preallocated exceptions that do not provide a stack trace. To disable completely the use of preallocated exceptions, use this new flag: `-XX:-OmitStackTraceInFastThrow`.

* `-XX:+OmitStackTraceInFastThrow` - Turns on using preallocated exception (no stack trace generated) immediately
* `-XX:-OmitStackTraceInFastThrow` - Disables using preallocated exceptions (stack traces are always generated)

Is this correct?
