### ISSUE TITLE
-XX:+UseStringDeduplication

### ISSUE THREAD

**Issue by sooheon** [FoxxMD/intellij-jvm-options-explained#2]
[This](https://blog.takipi.com/garbage-collectors-serial-vs-parallel-vs-cms-vs-the-g1-and-whats-new-in-java-8/) claims that one of the benefits of G1GC is string dedup. Is this true for IntelliJ VM? Should it be recommended?

**Comment by FoxxMD** [comment]
Interesting! I have no idea how this would affect intellij ¯\_(ツ)_/¯ If you can find some info explaining how this would affect it I would be happy to include it.
